### ISSUE TITLE
Rewrite scraping for 2022 ...and 2023

### ISSUE THREAD

**Issue by marksteward** [Jonty/open-house-london-data#3]
They've got rid of the nice map API. Looks like you can get listing IDs at `https://programme.openhouse.org.uk/calendar?page={1..28}`, and then fetch most of the data previously available from the individual listing page.

**Comment by Jonty** [comment]
The new map page is fairly easy to parse, so it might be easier to do that: https://programme.openhouse.org.uk/map

```
<ul class="markers">
  <li data-url="https://programme.openhouse.org.uk/map/881" data-latitude="51.4289264" data-longitude="-0.3241057">Landmark Arts Centre</li>
  <li data-url="https://programme.openhouse.org.uk/map/3751" data-latitude="51.3739677" data-longitude="-0.1429116">St Mary&#39;s Beddington</li>
  <li data-url="https://programme.openhouse.org.uk/map/3939" data-latitude="51.3660834" data-longitude="-0.1655658">Honeywood Museum</li>
  <li data-url="https://programme.openhouse.org.uk/map/8766" data-latitude="51.5083463" data-longitude="-0.1082762">1.20 Oxo Tower Wharf</li>
  ...
```

Curiously it looks like there's only ~200 listings on there though - is this open house a lot smaller, or are they just missing locations from the map?

The [tiny map info url](https://programme.openhouse.org.uk/map/2774) is interesting, but it doesn't have all the info about events sadly so we'll still need to parse the full page.

**Comment by Jonty** [comment]
Calendar indicates 667 results: https://programme.openhouse.org.uk/calendar

So is the website map just broken?

**Comment by marksteward** [comment]
Yeah, see the discussion on Slack. Might be possible to work around by doing each borough separately?

**Comment by Jonty** [comment]
It seems they've fixed the map so it has all the venues on it now, closing as ...didn't need to fix
