### ISSUE TITLE
Save favs/seen to google sheet

### ISSUE THREAD

**Issue by Jonty** [Jonty/open-house-london-data#8]
* Link your google account
* We create a spreadsheet in it if you've not already got it
* "Want to see" button adds them to the sheet / updates them if they exist
* "Mark as seen" button adds things to the sheet / updates them if they exist / col is null or year you saw it
* Add filters to the UI to show just faves, just seen, and hide seen
* Maybe allow you to give it a star rating out of five when you mark it as seen?
* Spreadsheet cols should be ID, Name, OH URL, Lat, Lon, Want to See, Year Seen, Rating

**Comment by marksteward** [comment]
I didn't see this but I've done a single bookmark flag, saved with ID, name, date and state.

Now need to work out how to do the filter, because mapbox doesn't make this easy.

**Comment by marksteward** [comment]
Filtering done with 2105d8c. To do seen in a meaningful way we need to reliably link venues across years.
